include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: ignore
    unused_local_variable: ignore
    prefer_final_fields: ignore
    dead_code: ignore
    unused_field: ignore
    duplicate_import: ignore
    depend_on_referenced_packages: ignore

linter:
  rules:
    - avoid_print: false
    - prefer_const_constructors: false
    - prefer_const_declarations: false
    - constant_identifier_names: false
