workflows:
  flutter-build:
    name: Flutter Build
    environment:
      flutter: stable
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle/caches
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release --split-per-abi
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
